language: ruby
rvm:
  - 2.0.0
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install nmap
  - sudo apt-get install wget
  - sudo apt-get install libcurl4-openssl-dev
  - 'cd vendor/Garmr && sudo python setup.py install && cd ../..'
  - 'cd vendor && wget https://github.com/iSECPartners/sslyze/releases/download/release-0.9/sslyze-0_9-linux64.zip && unzip sslyze-0_9-linux64.zip && cd ..'
  - 'cd vendor && wget http://downloads.sourceforge.net/project/dirb/dirb/2.03/dirb203.tar.gz && tar xvfz dirb203.tar.gz && cd dirb && ./configure && make && sudo cp dirb /usr/local/bin/ && cd ../../'
  - export SSLYZE_PATH="$TRAVIS_BUILD_DIR/vendor/sslyze-0_9-linux64/sslyze.py"
  - export SQLMAP_PATH="$TRAVIS_BUILD_DIR/vendor/sqlmap/sqlmap.py"
  - export DIRB_WORDLISTS="$TRAVIS_BUILD_DIR/vendor/dirb/wordlists"
before_script:
  - ./set_token.sh
  - bundle exec rake db:migrate
  - bundle exec rails s -d
script: 
  - bundle exec rake secure_pipeline:network_attack
  - bundle exec rake secure_pipeline:ssl_attack
  - bundle exec rake secure_pipeline:xss
  - bundle exec rake secure_pipeline:information_leakage
  - bundle exec rake secure_pipeline:sql_injection
